name: 02 - Build App Image

on:
  workflow_call:
    inputs:
      APP_TAG:
        description: 'App Tags'
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: demo-app
  APP_TAG: ${{ github.event.inputs.APP_TAG }}

jobs:
  build-app-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: demo-${{inputs.APP_TAG}}.jar

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push the image to GitHub registry
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{inputs.APP_TAG}}
          file: Dockerfile
          context: .
          no-cache: true
          build-args: |
            bundle_path=demo-$${{inputs.APP_TAG}}.jar
