name: Build Gradle bundle, container image and push to Git registry

on:
  workflow_dispatch: 
    inputs:
      APP_TAG:
        description: 'Enter tag name'
        required: true
        default: v0.0.0
        type: string
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: demo-app
  JDK_VERSION: 17
  APP_TAG: ${{ github.event.inputs.APP_TAG }}

jobs:
  fetch-tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: olegtarasov/get-tag@v2.1.3
      if: ${{github.env.APP_TAG == 'v0.0.0'}} 
      id: tagName
      with:
        tagRegexGroup: 1 # Optional. Default is 1.
    - name: Fetch tag
      run: echo "APP_TAG=${{ steps.tagName.outputs.tag }}" >> $env:GITHUB_ENV
      if: ${{github.env.APP_TAG == 'v0.0.0'}} 
    - name: Print the current tag
      run: echo ${{env.APP_TAG}}
 
  call-app-build:
    needs: fetch-tag
    uses: ./.github/workflows/build-app-maven.yml
    with:
      APP_TAG:  ${{github.env.APP_TAG}}
    
  build-app-image:
    needs: call-app-build
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4

    - uses: actions/download-artifact@v4
      with:
        name: demo-${{env.APP_TAG}}.jar

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push the image to Github registry
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ env.REGISTRY }}/${{ github.repository }}/${{env.IMAGE_NAME}}:${{env.APP_TAG}}
        file: Dockerfile
        context: .
        no-cache: true
        build-args: |
          bundle_path=demo-${{env.APP_TAG}}.jar