name: Build Java and Docker

on:
  workflow_dispatch:
    inputs:
      APP_TAG:
        description: 'Enter tag name'
        required: true
        default: v0.0.0
        type: string
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: demo-app
  APP_TAG: ${{ github.event.inputs.APP_TAG }}

jobs:
  fetch-tag:
    runs-on: ubuntu-latest
    outputs:
      APP_TAG:  ${{ steps.build_var.outputs.APP_TAG }}
    steps:
      - uses: actions/checkout@v4
      - uses: olegtarasov/get-tag@v2.1.3
        if: ${{ env.APP_TAG == '' }}
        id: tagName
        with:
          tagRegexGroup: 1 # Optional. Default is 1.

      - name: Git repo tag
        run: echo "APP_TAG=${{ steps.tagName.outputs.tag }}" >> $GITHUB_ENV
        if: ${{ env.APP_TAG == '' }}
      - name: User input tag
        run: echo "APP_TAG=${{ env.APP_TAG }}" >> $GITHUB_ENV
        if: ${{ env.APP_TAG != '' }}

      - name: Fetch final value
        run: echo "APP_TAG=$APP_TAG" >> $GITHUB_OUTPUT
        id: build_var

      

  test-variable:
    runs-on: ubuntu-latest
    needs: fetch-tag
    steps:
      - uses: actions/checkout@v4 
      - run: echo "check the variable ${{ needs.fetch-tag.outputs.APP_TAG }}"     
  call-app-build:
    needs: fetch-tag
    uses: ./.github/workflows/build-app-maven.yml
    with:
      APP_TAG:  ${{ needs.fetch-tag.outputs.APP_TAG }}

  build-app-image:
    needs: [call-app-build,fetch-tag]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: demo-${{needs.fetch-tag.outputs.APP_TAG}}.jar

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push the image to GitHub registry
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ needs.fetch-tag.outputs.APP_TAG }}
          file: Dockerfile
          context: .
          no-cache: true
          build-args: |
            bundle_path=demo-${{ needs.fetch-tag.outputs.APP_TAG }}.jar
