name: PoC of Github

on:
  workflow_dispatch: 
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'
       

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: demo-app
  JDK_VERSION: 17

jobs:


  build-app-image:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4

    - uses: olegtarasov/get-tag@v2.1.3
      id: tagName
      with:
      # tagRegex: "foobar-(.*)"
      # Optional: Returns specified group text as the tag name. Full tag string is returned if regex is not defined.
       tagRegexGroup: 1 # Optional. Default is 1.

    - name: run tag
      run: echo "${{ steps.tagName.outputs.tag }}"