name: PoC of Github

on:
  workflow_dispatch: 
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'
       

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: demo-app
  JDK_VERSION: 17

jobs:


  build-app-image:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4


    - name: run tag
      run: echo $GIT_TAG_NAME