name: PoC of Github

on:
  workflow_dispatch: 
    inputs:
      APP_TAG:
        description: 'Enter tag name'
        required: true
        default: v0.0.0
        type: string
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: demo-app
  JDK_VERSION: 17
  APP_TAG: ${{ github.event.inputs.APP_TAG }}
jobs:
  fetch-tag:
    runs-on: ubuntu-latest
    outputs:
      APP_TAG_2:  ${{ steps.build_var_2.outputs.APP_TAG_2 }}
    steps:
      - uses: actions/checkout@v4
      - uses: olegtarasov/get-tag@v2.1.3
        if: ${{ env.APP_TAG == '' }}
        id: tagName
        with:
          tagRegexGroup: 1 # Optional. Default is 1.
      - name: Fetch tag
        id: build_var
        run: echo "APP_TAG=${{ steps.tagName.outputs.tag }}" >> $GITHUB_OUTPUT
        if: ${{ env.APP_TAG == '' }}

      - name: Fetch final value
        run: echo "APP_TAG_2=Test_value" >> $GITHUB_OUTPUT
        id: build_var_2
      

  test-variable:
    runs-on: ubuntu-latest
    needs: fetch-tag
    steps:
      - uses: actions/checkout@v4 
      - run: echo "check the variable ${{ needs.fetch-tag.outputs.APP_TAG_2 }}"  

